entryPoints:
  web:
    address: ":8081"

  traefik:
    address: ":8082"

api:
  dashboard: true
  insecure: true  # Dashboard'a IP üzerinden erişebilmek için (üretimde devre dışı bırakılmalı!)

providers:
  file:
    filename: traefik.yml

log:
  level: DEBUG

