http:
  routers:
    task-service-router:
      rule: "Header(`X-Service`, `task-service`)"
      service: task-service
      entryPoints:
        - web
    comment-service-router:
      rule: "Header(`X-Service`, `comment-service`)"
      service: comment-service
      entryPoints:
        - web

    dashboard-router:
      rule: "PathPrefix(`/dashboard`)"
      service: api@internal
      entryPoints:
        - traefik

  services:
    task-service:
      loadBalancer:
        servers:
          - url: "http://127.0.0.1:6061"
    comment-service:
      loadBalancer:
        servers:
          - url: "http://127.0.0.1:6060"
  
  